### ISSUE TITLE
Add AlwaysFalse Voter

### ISSUE THREAD

**Issue by debreczeniandras** [elbcoast/ECNFeatureToggleBundle#8]
During composer hooks, features.yml could automatically be populated based on the features.yml.dist file via the Incenteev buildparameters script.

In production however, these features should be added as AlwaysFalse to prevent these features to automatically take into consideration.

For this purpose an AlwaysFalse Voter should be created.

**Comment by elbcoast** [comment]
Added in 1.1.0!
